# Site settings
title: jay pinho
email: jaypinho@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  data.tech.media.politics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.jaypinho.com" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title/
twitter_username: jaypinho
github_username:  jaypinho
timezone: America/New_York
paginate: 5
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jay Pinho"
      comments: true

# Build settings
markdown: kramdown
